metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
  - module: vsphere
    metricsets:
      - datastore
      - host
      - virtualmachine
    enabled: true
    period: 5s
    hosts: ["https://vsphere:443/sdk"]
    username: "user"
    password: "pass"
    insecure: true

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  index: "metricbeatlocal-%{[agent.version]}-%{+yyyy.MM.dd}"
  username: ''
  password: ''

setup.dashboards.enabled: true

setup.kibana:
  host: "kibana:5601"
  username: ""
  password: ""

setup.template.name: "metricbeatlocal"
setup.template.pattern: "metricbeatlocal-*"
